// Shared API adapter: official static master data works on GitHub Pages; case writes require the hosted backend.
export const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
export const STATIC_BASE=import.meta.env.BASE_URL||'/';
let masterCache=null;
async function loadMaster(){if(masterCache)return masterCache;const r=await fetch(`${STATIC_BASE}data/bihar_official_master_data.json`);if(!r.ok)throw new Error('Official master data unavailable');const raw=await r.json();const records=Array.isArray(raw.records)?raw.records:[];const districts=[],subdivisions=[],circles=[];const dm=new Map(),sm=new Map(),cm=new Map();for(const row of records){const dn=String(row.district||'').trim(),sn=String(row.subdivision||'').trim(),cn=String(row.circle||'').trim();if(!dn)continue;let d=dm.get(dn);if(!d){d={id:`d-${districts.length+1}`,name:dn};dm.set(dn,d);districts.push(d)}if(!sn)continue;const sk=`${d.id}|${sn}`;let sub=sm.get(sk);if(!sub){sub={id:`s-${subdivisions.length+1}`,district_id:d.id,name:sn};sm.set(sk,sub);subdivisions.push(sub)}if(!cn)continue;const ck=`${sub.id}|${cn}`;if(!cm.has(ck)){const c={id:`c-${circles.length+1}`,subdivision_id:sub.id,name:cn,status:row.status||'active'};cm.set(ck,c);circles.push(c)}}masterCache={...raw,districts,subdivisions,circles};return masterCache}
async function staticDistricts(){const m=await loadMaster();return m.districts}
async function staticSubs(id){const m=await loadMaster();return m.subdivisions.filter(x=>String(x.district_id)===String(id))}
async function staticCircles(id){const m=await loadMaster();return m.circles.filter(x=>String(x.subdivision_id)===String(id))}
export async function api(path,options={}){if(!API){const method=(options.method||'GET').toUpperCase();if(method==='GET'&&path==='/districts')return staticDistricts();if(method==='GET'&&path.startsWith('/districts/')&&path.endsWith('/subdivisions'))return staticSubs(path.split('/')[2]);if(method==='GET'&&path.startsWith('/subdivisions/')&&path.endsWith('/circles'))return staticCircles(path.split('/')[2]);if(method==='GET'&&path==='/dashboard')return {totals:{cases:0,districts:0,resolved:0},byDistrict:[]};throw new Error('यह सुविधा चलाने के लिए backend API configure करना आवश्यक है। अभी GitHub Pages पर केवल आधिकारिक master data और सार्वजनिक कानूनी जानकारी उपलब्ध है।')}const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
