import React,{useEffect,useMemo,useState} from 'react';

import {ArrowRight,Activity,AlertTriangle,BarChart3,BookOpen,CheckCircle2,ChevronRight,Clock3,Database,ExternalLink,Filter,GitBranch,Landmark,LayoutDashboard,LockKeyhole,MapPinned,Menu,RefreshCw,Scale,Search,ShieldCheck,Users,X,FileText,ClipboardList} from 'lucide-react';

import {Stat,Info} from '../components/Common.jsx';

import {api} from '../services/api.js';

export function AdminPage(){const [token,setToken]=useState(localStorage.getItem('blta_admin_token')||'');const [status,setStatus]=useState(null);const [overview,setOverview]=useState(null);const [msg,setMsg]=useState('');const load=async()=>{try{const h={'x-admin-token':token};const [s,o]=await Promise.all([api('/admin/master-data/status',{headers:h}),api('/admin/overview',{headers:h})]);setStatus(s);setOverview(o);setMsg('')}catch(e){setMsg(e.message)}};const sync=async()=>{try{setMsg('Syncing official master data…');const r=await api('/admin/master-data/sync',{method:'POST',headers:{'x-admin-token':token}});setMsg(`Synced ${r.districtCount} districts / ${r.subdivisionCount} subdivisions / ${r.circleCount} circles`);await load()}catch(e){setMsg(e.message)}};return <main className="page"><div className="pageTitle"><label>ADMIN / DATA INTEGRITY CONTROL ROOM</label><h1>Master data, cases और legal sources</h1><p>Official master data is seeded locally from the verified JSON; live sync is optional and guarded against partial imports.</p></div><div className="adminBar"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin token"/><button onClick={()=>{localStorage.setItem('blta_admin_token',token);load()}}>Load dashboard</button><button onClick={sync}><RefreshCw size={16}/> Sync Official Master Data</button></div>{msg&&<div className="result">{msg}</div>}<div className="stats"><Stat n={status?.counts?.districts||0} t="Active districts"/><Stat n={status?.counts?.subdivisions||0} t="Active subdivisions"/><Stat n={status?.counts?.circles||0} t="Active circles"/><Stat n={overview?.totalCases||0} t="Cases"/></div>{status?.sync&&<div className="sourceBox"><b>Last master-data sync: {status.sync.status}</b><span>{status.sync.message||''} • Source: {status.sourceUrl}</span></div>}<div className="cards"><Info icon={<Database/>} n="01" t="Master-data integrity" d="Partial live imports are rejected; local verified dataset remains available if government source is temporarily unreachable."/><Info icon={<Search/>} n="02" t="Duplicate control" d="Database unique constraint: District + Case Number + Case Year."/><Info icon={<BookOpen/>} n="03" t="Legal source control" d="Every legal entry carries official source, owner, verification date and current status."/><Info icon={<LockKeyhole/>} n="04" t="Privacy boundary" d="Public dashboard should expose aggregate research—not private citizen contact/identity data."/></div></main>}
