import React,{useEffect,useMemo,useState} from 'react';

import {ArrowRight,Activity,AlertTriangle,BarChart3,BookOpen,CheckCircle2,ChevronRight,Clock3,Database,ExternalLink,Filter,GitBranch,Landmark,LayoutDashboard,LockKeyhole,MapPinned,Menu,RefreshCw,Scale,Search,ShieldCheck,Users,X,FileText,ClipboardList} from 'lucide-react';

import {api} from '../services/api.js';

export function DistrictsPage({districts,selected,setSelected}){const [q,setQ]=useState('');const filtered=useMemo(()=>districts.filter(d=>d.name.toLowerCase().includes(q.toLowerCase())),[districts,q]);return <main className="page"><div className="pageTitle"><label>BIHAR DISTRICT NETWORK</label><h1>38 जिले • वास्तविक administrative hierarchy</h1><p>Master dataset में official District → Subdivision → Circle hierarchy embedded है। Live sync उपलब्ध होने पर source को पुनः verify किया जा सकता है।</p></div><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="जिला खोजें..."/></div><span>{filtered.length} जिले</span></div><div className="districtGrid">{filtered.map((d,i)=><button className={String(selected)===String(d.id)?'selected':''} onClick={()=>setSelected(String(d.id))} key={d.id}><span>{String(i+1).padStart(2,'0')}</span><b>{d.name}</b><ArrowRight size={17}/></button>)}</div>{selected&&<DistrictPanel districtId={selected} districts={districts}/>}</main>}

export function DistrictPanel({districtId,districts}){const d=districts.find(x=>String(x.id)===String(districtId));const [subs,setSubs]=useState([]);const [sub,setSub]=useState('');const [circles,setCircles]=useState([]);const [circle,setCircle]=useState('');useEffect(()=>{api(`/districts/${districtId}/subdivisions`).then(setSubs).catch(()=>setSubs([]));setSub('');setCircles([]);setCircle('')},[districtId]);useEffect(()=>{if(sub)api(`/subdivisions/${sub}/circles`).then(setCircles).catch(()=>setCircles([]));else setCircles([]);setCircle('')},[sub]);return <div className="selectedPanel"><MapPinned/><div className="panelWide"><b>{d?.name}</b><p>यहाँ database से वास्तविक Subdivision और Circle records आते हैं। कोई अनुमानित administrative name publish नहीं किया जाता।</p><div className="selectors"><select value={sub} onChange={e=>setSub(e.target.value)}><option value="">Subdivision चुनें</option>{subs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select disabled={!sub} value={circle} onChange={e=>setCircle(e.target.value)}><option value="">{sub?`Circle चुनें (${circles.length})`:'पहले Subdivision चुनें'}</option>{circles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>{sub&&<div className="dataNote"><CheckCircle2 size={16}/> {subs.length} official subdivision records loaded • {circles.length} Circle records for selected subdivision{sub&&circle?` • Selected Circle ID ${circle}`:''}</div>}</div></div>}
