import React,{useEffect,useMemo,useState} from 'react';

import {ArrowRight,Activity,AlertTriangle,BarChart3,BookOpen,CheckCircle2,ChevronRight,Clock3,Database,ExternalLink,Filter,GitBranch,Landmark,LayoutDashboard,LockKeyhole,MapPinned,Menu,RefreshCw,Scale,Search,ShieldCheck,Users,X,FileText,ClipboardList} from 'lucide-react';

import {Metric,Info} from '../components/Common.jsx';

export function HomePage({go,districts,setSelected}){return <main className="ti-home">
 <section className="ti-hero"><div className="ti-heroCopy"><div className="ti-eyebrow"><ShieldCheck size={15}/> PUBLIC INTEREST • TRANSPARENCY • ACCOUNTABILITY</div><p className="ti-kicker">एक जनहित पहल</p><h1>जब जनता की बात<br/>न सुनी जाए, तो<br/><em>आवाज़ कहाँ दर्ज हो?</em></h1><p className="ti-lead">लोकतंत्र में जनता केवल वोट देने के लिए नहीं—सुनी जाने, सम्मान पाने और जवाबदेही की अपेक्षा रखने के लिए भी है। <b>Transparency Indicator</b> नागरिक अनुभवों, नियमों और उपलब्ध तथ्यों को जोड़कर समस्या को समझने और सुधार की दिशा खोजने का प्रयास है।</p><div className="ti-actions"><button onClick={()=>go('feedback')}>नागरिक अनुभव दर्ज करें <ArrowRight size={18}/></button><button className="ti-secondary" onClick={()=>document.getElementById('ti-method')?.scrollIntoView({behavior:'smooth'})}>हमारी कार्यप्रणाली जानें <ChevronRight size={17}/></button></div><div className="ti-promise"><ShieldCheck size={17}/><span>पहले तथ्य। फिर विश्लेषण। अंततः सुधार का प्रयास।</span></div></div>
 <div className="ti-visual"><div className="ti-orbit ti-orbitOne"></div><div className="ti-orbit ti-orbitTwo"></div><div className="ti-core"><div className="ti-coreIcon"><Scale size={34}/></div><span>TRANSPARENCY</span><b>जनता ↔ व्यवस्था</b><small>सवाल से जवाबदेही तक</small></div><div className="ti-float ti-floatTop"><Users size={17}/><span>जनता की बात</span></div><div className="ti-float ti-floatRight"><BookOpen size={17}/><span>तथ्य और नियम</span></div><div className="ti-float ti-floatBottom"><Activity size={17}/><span>सुधार की दिशा</span></div><div className="ti-visualFoot"><span>LISTEN</span><i></i><span>VERIFY</span><i></i><span>IMPROVE</span></div></div></section>
 <section className="ti-question"><div className="ti-sectionLabel">एक जरूरी सवाल</div><h2>क्या शिकायत दर्ज हो जाना ही पर्याप्त है?</h2><p>नागरिक को यह भी समझ में आना चाहिए कि लागू नियम क्या हैं, प्रक्रिया किस चरण में है, उपलब्ध जानकारी क्या बताती है और आगे कौन-सा रास्ता अपनाया जा सकता है।</p><div className="ti-questionMark">“</div></section>
 <section className="ti-work" id="ti-method"><div className="ti-heading"><div><div className="ti-sectionLabel">हम क्या करने का प्रयास करेंगे</div><h2>सिर्फ समस्या दर्ज नहीं—<br/><em>समस्या को समझना भी।</em></h2></div><p>नागरिक अनुभवों को व्यवस्थित करना, उन्हें संबंधित नियमों और उपलब्ध आधिकारिक जानकारी से जोड़ना और सुधार के अवसर पहचानना—यही हमारी कार्यदिशा है।</p></div><div className="ti-featureGrid"><article><span className="ti-number">01</span><div className="ti-featureIcon"><Users size={22}/></div><h3>जनता की बात</h3><p>नागरिकों की समस्या, अनुभव और सुझाव को एक व्यवस्थित रूप में दर्ज करने का प्रयास।</p><button onClick={()=>go('feedback')}>अनुभव दर्ज करें <ArrowRight size={15}/></button></article><article><span className="ti-number">02</span><div className="ti-featureIcon"><BookOpen size={22}/></div><h3>तथ्य और नियम</h3><p>कानून, सरकारी निर्देश और उपलब्ध आधिकारिक स्रोतों से प्रक्रिया को सरल भाषा में समझना।</p><button onClick={()=>go('law')}>कानून समझें <ArrowRight size={15}/></button></article><article><span className="ti-number">03</span><div className="ti-featureIcon"><GitBranch size={22}/></div><h3>प्रक्रिया की निगरानी</h3><p>जहाँ रिकॉर्ड उपलब्ध हों, वहाँ तारीख, प्राधिकारी, शिकायत संख्या और अगला कदम समझना।</p><button onClick={()=>go('grievance')}>शिकायत यात्रा <ArrowRight size={15}/></button></article><article><span className="ti-number">04</span><div className="ti-featureIcon"><BarChart3 size={22}/></div><h3>साझा समस्याएँ, बेहतर सुझाव</h3><p>बार-बार सामने आने वाले मुद्दों का समग्र विश्लेषण और व्यावहारिक सुधार के सुझाव।</p><button onClick={()=>go('research')}>विश्लेषण देखें <ArrowRight size={15}/></button></article></div></section>
 <section className="ti-integrity"><div className="ti-integrityText"><div className="ti-sectionLabel">हमारी प्रतिबद्धता</div><h2>न पक्षपात।<br/>न पूर्वनिर्धारित निष्कर्ष।</h2><p>किसी व्यक्ति, दल, सरकार या संस्था के पक्ष या विरोध में पहले से निष्कर्ष लेकर नहीं चलेंगे। विश्वसनीयता का आधार होगा—तथ्य, स्रोत और अपनी सीमाओं के बारे में स्पष्टता।</p><button onClick={()=>go('reports')}>हमारी जवाबदेही के सिद्धांत <ArrowRight size={16}/></button></div><div className="ti-rules"><div><CheckCircle2 size={19}/><span><b>शिकायत, प्रमाणित दोष नहीं</b><small>नागरिक के आरोप और अनुभव को उसी रूप में पहचाना जाएगा।</small></span></div><div><CheckCircle2 size={19}/><span><b>तथ्य और निष्कर्ष अलग</b><small>प्रक्रियागत चिंता, सत्यापित अनियमितता और आधिकारिक निष्कर्ष एक नहीं हैं।</small></span></div><div><CheckCircle2 size={19}/><span><b>स्रोत और सीमाएँ स्पष्ट</b><small>अधूरी जानकारी को सत्यापित तथ्य बताकर प्रस्तुत नहीं किया जाएगा।</small></span></div><div><CheckCircle2 size={19}/><span><b>समस्या केंद्र में, व्यक्ति नहीं</b><small>उद्देश्य दोष तय करना नहीं, जवाबदेही और सुधार की संभावना समझना है।</small></span></div></div></section>
 <section className="ti-bihar"><div className="ti-biharMap"><div className="ti-mapBadge">पहली पहल</div><div className="ti-mapLetters">बिहार</div><div className="ti-mapCaption">CITIZEN-FIRST • FACT-LED</div></div><div className="ti-biharCopy"><div className="ti-sectionLabel">बिहार से शुरुआत</div><h2>भूमि अधिकार एवं<br/><em>पारदर्शिता अभियान — बिहार</em></h2><p>दाखिल-खारिज, जमाबंदी, राजस्व अभिलेख और शिकायत-निवारण की प्रक्रियाएँ आम परिवारों के अधिकारों और रोज़मर्रा के जीवन से जुड़ी हैं। हमारी पहली केंद्रित पहल इन प्रक्रियाओं को समझने, नियमों को सरल बनाने और नागरिक अनुभवों में दिखने वाले साझा मुद्दों का अध्ययन करने का प्रयास करेगी।</p><div className="ti-topicTags"><span>दाखिल-खारिज</span><span>जमाबंदी</span><span>राजस्व प्रक्रिया</span><span>शिकायत यात्रा</span></div><div className="ti-biharActions"><button onClick={()=>go('process')}>दाखिल-खारिज की यात्रा <ArrowRight size={16}/></button><button className="ti-linkBtn" onClick={()=>go('districts')}>जिला नेटवर्क देखें <ChevronRight size={16}/></button></div></div></section>
 <section className="ti-steps"><div className="ti-sectionLabel">एक सरल कार्यपद्धति</div><h2>सुनें <span>→</span> समझें <span>→</span> जाँचें <span>→</span> सुधार सुझाएँ</h2><p>हम हर समस्या के समाधान की गारंटी नहीं देते। हमारा प्रयास है कि उपलब्ध जानकारी के आधार पर नागरिक को समस्या समझने, उचित आधिकारिक प्रक्रिया पहचानने और सुधार के लिए उपयोगी तथ्य सामने रखने में मदद मिले।</p><div className="ti-disclaimer"><ShieldCheck size={18}/><span><b>एक महत्वपूर्ण स्पष्टता</b> Transparency Indicator किसी सरकारी प्राधिकरण, न्यायालय या वैधानिक शिकायत-निवारण मंच का विकल्प नहीं है। आवश्यकता के अनुसार संबंधित आधिकारिक प्रक्रिया का उपयोग अलग से करें।</span></div></section>
 <section className="ti-lastCall"><div><span>YOUR VOICE MATTERS</span><h2>बदलाव की शुरुआत<br/>एक सवाल से होती है।</h2><p>अपनी बात रखें। तथ्यों को समझें। जवाबदेही की दिशा में आगे बढ़ें।</p></div><button onClick={()=>go('feedback')}>अपना नागरिक अनुभव दर्ज करें <ArrowRight size={18}/></button></section>
 </main>}
